### ISSUE TITLE
The JSON value could not be converted

### ISSUE THREAD

**Issue by jparadaa** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#16]
Hola,

Obtengo error:

 {"type"=>"https://tools.ietf.org/html/rfc7231#section-6.5.1", "title"=>"One or more validation errors occurred.", "status"=>400, "traceId"=>"00-0e23bba8b70500fe5b43b6538ceac10b-ba11e5d00b14a7cc-00", "errors"=>{"apiRequest"=>{"The apiRequest field is required."}, "$.model.documento.fecha"=>{"The JSON value could not be converted
to System.DateTime. Path: $.model.documento.fecha |

lo que veo, al parecer el problema es el dato fecha, en qué formato debo enviar la fecha?

**Comment by AndresRamos** [comment]
Las fechas deben tener el formato **ISO 8601** por ejemplo `2019-07-26T16:59:57`.

¿En dónde te está marcando este error?
