### ISSUE TITLE
Apertura ventana interfaz empresa contabilidad

### ISSUE THREAD

**Issue by jparadaa** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#18]
Al intentar crear el request tipo documento pedido, me desplegó la ventana para ingreso a contabilidad, se trata de una empresa que efectivamente tiene interfaz con el sistema contable.

**Comment by AndresRamos** [comment]
Al momento de abrir la empresa de Comercial por SDK, si esta está ligada a una empresa CONTPAQi Contabilidad, efectivamente como dices el sincronizador te pide las credenciales de CONTPAQi Contabilidad. Si lo cierras en vez de ingresar las credenciales te marca error y truena el sincronizador.

Existe un proceso para que no te pida las credenciales manualmente, pero este proceso no lo eh implementado en la version 2.3.0. Voy a implementar este proceso en la version 2.4.0. 

Por lo pronto lo que puedes hacer es ingresar las credenciales correctas de Contabilidad y darle OK. Mientras el sincronizador no cambie de empresa solo te las pedirá esa sola vez.

**Comment by jparadaa** [comment]
Gracias Andrés, implementaste la mejora para indicar si es una empresa con interfaz contable en la v2.4.0
