### ISSUE TITLE
Estatus code 404 en Get Request By Id

### ISSUE THREAD

**Issue by jparadaa** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#19]
Mi flujo de desarrollo es que una vez que obtengo el id de mi request document, inmediatamente llamo a request by id
y estoy obteniendo un estatus code 404, Resource not found.

Pero el documento se crea correctamente en el sistema Comercial.

Alguna idea qué puedo tracear para ver por qué recibo este error,

**Comment by AndresRamos** [comment]
1. ¿Como estas buscando la solicitud?
2. ¿Cual es el error que te manda la API? ¿El JSON?
3. ¿Puedes tomar el Id y con Postman validar que si te regrese la solicitud?

**Comment by jparadaa** [comment]
Ups mi culpa, lo siento... me faltaba finalizar la url con /
