### ISSUE TITLE
Propiedad "WaitTime" archivo configuración appsettings.json

### ISSUE THREAD

**Issue by jparadaa** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#31]
Actualizando el día de hoy a la versión 2.4.0, veo que en el archivo appsettings.json no está presente la propiedad WaitTime

**Comment by AndresRamos** [comment]
Asi es, en la version 2.4.0 el sincronizador ya no está periódicamente consultando a la API para ver si hay solicitudes nuevas. Ahora la API a través de SignalR notifica al cliente en tiempo real cuando hay solicitudes pendientes por procesar y es ahi cuando el sincronizador hace la consulta directamente a la API.

**Comment by jparadaa** [comment]
Enterado, Gracias.
