### ISSUE TITLE
Error Numero 130101

### ISSUE THREAD

**Issue by desarrollo5moti** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#45]
Que tal Andrés la api me tira el siguiente error El documento ya existe Numero: 130101 pero no se a que se deba me podrías indicar por favor?

**Comment by AndresRamos** [comment]
Quiere decir que la serie y el folio del concepto con el que estas intentando crear el documento ya existe. 

Tengo unas dudas:
1. ¿Estas asignando manualmente el folio?
2. Tienes la opción `buscarSiguienteFolio` con el valor `true`?

**Comment by desarrollo5moti** [comment]
Muchas gracias como nos indicaste en soporte remoto mas que nada cada concepto debe tener su propio Folio y Serie para hacer que sean independientes y no se afecte con otros conceptos.

**Comment by desarrollo5moti** [comment]
Gracias
