### ISSUE TITLE
Error de cors

### ISSUE THREAD

**Issue by lunarog** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#46]
Que tal
Estamos intentando hacer la integración del api contpaqiapim en nuestra aplicación.
sin embargo, estamos recibiendo un bloqueo de CORS al consumirla desde http://localhost:8080

 
![Captura de pantalla 2023-10-26 180050](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial.Api/assets/46695824/ff4a5dd0-f9a5-42ba-9aa9-8a883f760a5c)

**Comment by AndresRamos** [comment]
No puedes comunicarte con la API desde el front end. Debes llamarla desde el backend.
