### ISSUE TITLE
ShutdownTime no termina el sincronizador

### ISSUE THREAD

**Issue by jparadaa** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#47]
Entiendo que en la versión 2.5.0 se indica que se corrigió un problema con el sincronizador, pero en mi caso en el archivo appsettings.json he configurado "ShutdownTime": "17:45:00" y no termina el sincronizador en la hora indicada.

**Comment by AndresRamos** [comment]
Hola Javiar, gracias por reportar este error. Después de hacer un análisis más completo si pude comprobar que el sincronizador no estaba respetando el tiempo de apagado.

Este error se corrige en la actualización [v3.0.0](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial.Api/releases/tag/v3.0.0) que acabo de liberar.
