### ISSUE TITLE
Error al Asignar el documento.

### ISSUE THREAD

**Issue by desarrollo5moti** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#51]
Buen día Andrés al momento de mandar timbrar una factura nos marca Mensaje:[Error al Asignar el documento.] Numero:[160603]
lo cual tenemos duda de a que se pueda deber.

De antemano gracias por tu valioso ayuda.

**Comment by AndresRamos** [comment]
Estas creando una facturar enviando la solicitud `CrearFacturaRequest`? Se creo la factura correctamente, pero no se timbro?

Si el documento estuviera mal formado mandaría otro mensaje de error. Ese error creo que tiene que ver con los certificados para el timbrado. ¿Podrías confirmar que estas utilizando la contraseña correcta? Estas utilizando certificados de prueba o los de tu empresa?

Puedes realizar lo siguiente:

1. ¿Si el documento se creó podrías ir a buscarlo en CONTPAQi Comercial?
2. Intenta timbrar manualmente el documento utilizando la contraseña que mandaste en la solicitud.
4. Te marca algún error mas especifico?

**Comment by desarrollo5moti** [comment]
Tenías razón Andrés ya nos permitió timbrar al parecer fue debido a que el proveedor del contpaq cambio los certificados y apenas les dejo la contraseña anterior por eso no se podía timbrar muchas gracias.
