### ISSUE TITLE
Al utilizar GenerarDocumentoDigitalRequest deja bloqueado el documento

### ISSUE THREAD

**Issue by jparadaa** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#62]
Utilizo GenerarDocumentoDigitalRequest para generar un archivo pdf en mi caso un documento cotización, el pdf se genera correctamente pero queda bloqueado el documento en Comercial Premium

**Comment by AndresRamos** [comment]
Podrias proporcionar el concepto de documento que esta utilizando para crear el documento? Y tambien el nombre de la plantilla que estas utilizando? Es alguna de las predeterminadas que vienen por default?

**Comment by jparadaa** [comment]
El concepto es Cotización Documento modelo - cotización, es un concepto que yo creado con descripción

_"Cotización NUBE usuario"_

**Comment by AndresRamos** [comment]
Ya lo corregi, se asocio el PR que lo corrige. Esto debo salir en la siguiente version.
