### ISSUE TITLE
Al utilizar EliminarDocumentoRequest recibo error No modificable-Impreso

### ISSUE THREAD

**Issue by jparadaa** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#71]
En la llamada CrearDocumentoRequest, hay alguna forma de indicar que el documento, en mi caso una cotización, NO quede como ***No modificable-Impreso***, ya que ahora intento utilizar EliminarDocumentoRequest y recibo justo ese error

**Comment by AndresRamos** [comment]
Podrias hacer lo siguiente:

1. Crea el documento de tipo cotizacion
2. Mandalo a eliminar

Se elimina? Solo para validar que es la solicitud de generar documentos digitales la que lo marca como no modificable.

**Comment by AndresRamos** [comment]
Revisando y haciendo pruebas, la casilla de `no modificable - impreso` ocurre pues cuando se "imprime" o se genera el documento digital de un documento. Esto se puede considerar una caracteristica, talvez de seguridad, y si quieres eliminar el documento debes desasignar la casilla. Esto lo puedes hacer en el sistema.

Para hacer con la API debe modificar el campo `CIMPRESO` con el valor `0`.

```json
{
  "$type": "ActualizarDocumentoRequest",
  "model": {
    "llaveDocumento": {
      "conceptoCodigo": "1",
      "serie": "",
      "folio": 2
    },
    "datosDocumento": {
      "CIMPRESO": "0"
    }
  },
  "options": {
    "cargarDatosExtra": false
  }
}
```

**Comment by jparadaa** [comment]
Perfecto, en cuanto liberes la nueva versión, realizaré la prueba y comento.
