### ISSUE TITLE
El reporteador de errores arroja mensajes de error de otros documentos al intentar timbrar

### ISSUE THREAD

**Issue by JuliusLancelot** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api#89]
Es muy común que el mensaje de error arrojado por la API no corresponde al proceso que se está intentando realizar, sino a otro proceso. De manera que es confuso tratar de corregir errores en un documento al intentarlo timbrar ya que no corresponden entre sí los mensajes de error. 

Saludos!

**Comment by AndresRamos** [comment]
Estas corriendo la última version de CONTPAQi Comercial? La version 9.1.1?

En esta version:

> Folio-Ticket:D511232-2023090110001848
> Ahora, al utilizar la función fEmitirDocumento del SDK, se mostrará el mensaje correspondiente al momento de timbrar documentos.
> Anteriormente, al utilizar la función, mostraba el mensaje: "Se está intentando usar memoria protegida" aun cuando el documento se timbraba correctamente.

Podrias actualizar y ver si te sigue marcando errores equivocados?

**Comment by JuliusLancelot** [comment]
Tengo la versión 9.0.1. Actualizo y te aviso!
